# Generated by Django 5.1.3 on 2024-11-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookname", models.CharField(max_length=20, verbose_name="書名")),
                ("author", models.CharField(max_length=20, verbose_name="作者")),
                ("publisher", models.CharField(max_length=20, verbose_name="出版社")),
                ("pubdate", models.DateField(verbose_name="出版日期")),
                ("price", models.IntegerField(verbose_name="定價")),
                ("content", models.TextField(verbose_name="詳細內容")),
            ],
        ),
    ]
